package com.handsfree.be.constant;

public enum NotificationType {
    JOB_INTEREST_RECEIVED,
    CANDIDATE_ACCEPTED,
    CANDIDATE_REJECTED,
    PAYMENT_RECEIVED,
    CONNECTION_SUCCEEDED,
    CHAT_MESSAGE_RECEIVED,
    REPORT_RESOLVED,
    REPORT_REJECTED,
    IDENTITY_REVIEWED,
    RATING_RECEIVED
}
